### ISSUE TITLE
Found some bugs

### ISSUE THREAD

**Issue by Xeneht** [IMXNOOBX/fstick#1]
**Wifi Management**
- `Scan AP` enters directly when passing through it
- `Deauth/Clone AP/Spam AP` and some other options not showing in green when are toggled

**BLE Utils**
- Using `@everyone` after 60s all the circles are on the limit of the screen and if you re-enter the screen will be empty 
- Using `@everyone` if you re-enter the circles will be in the same positions as when you exited and will not be reset
- Using `@everyone` if you exit it using side buttons instead of middle button the menu navigation will be very bugged

**Info**
- `Donate` enters directly when passing through it
- `Credits` enters directly when passing through it

**Comment by IMXNOOBX** [comment]
Ups!

Thanks for pointing them out. I will work to fix them!

**Comment by IMXNOOBX** [comment]
This issue has been solved, thanks for your help!
