### ISSUE TITLE
Please consider using the 433Mhz receiver and transmitter from M5Stack #31

### ISSUE THREAD

**Issue by shadowdoggie** [IMXNOOBX/fstick#10]
Hello IMXNOOBX :)

I highly admire what you're doing, and i am really hoping you could take a look at some of the modules/hats, i found for the m5stick, that you can connect all at the same time, using a 1 to 3 hub expansion unit, that they also sell here: https://shop.m5stack.com/products/mini-hub-module

Here are the 433 Mhz modules:
Receiver: https://shop.m5stack.com/products/rf-unit-433mhz-receiver-syn513r
Transmitter: https://shop.m5stack.com/products/rf-unit-433mhz-transmitter-syn115
IR Receiver + Transmitter: https://shop.m5stack.com/products/ir-unit
RFID module: https://shop.m5stack.com/products/rfid-unit-2-ws1850s

p.s.
Maybe they have some more interesting modules/hats?
I don't have these modules myself sadly (yet).

Thank you very much in advance!

**Comment by IMXNOOBX** [comment]
I would really enjoy working with the hats for the device, but im not currently planning to adquire any of them, im sorry
