### ISSUE TITLE
rogue ap and ir

### ISSUE THREAD

**Issue by hunt3rbb666NotFound** [IMXNOOBX/fstick#13]
Brother, rogue ap and ir not working. It would also be nice if I could clone or choose the target for the deauth. I hope it's a nice idea for the next release. Nice project.

**Comment by IMXNOOBX** [comment]
https://docs.imxnoobx.com/fstick/wifi-utilities#rogue-access-points

The ir module should work fine, not all devices are supported, im working to find a more extensive and complete list
