### ISSUE TITLE
Issue - Multiple definition of `ieee80211_raw_frame_sanity_check`

### ISSUE THREAD

**Issue by hnmendes** [IMXNOOBX/fstick#5]
When i try to run locally on arduino IDE it throws this error:

c:/users/myuser/appdata/local/arduino15/packages/m5stack/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\MyUser\AppData\Local\Arduino15\packages\m5stack\hardware\esp32\2.0.8/tools/sdk/esp32/lib\libnet80211.a(ieee80211_output.o): in function `ieee80211_raw_frame_sanity_check':
(.text.ieee80211_raw_frame_sanity_check+0x5c): multiple definition of `ieee80211_raw_frame_sanity_check'; C:\Users\MyUser\AppData\Local\Temp\arduino\sketches\A063D69E09EFA32C67166B0C3DDA4AEB\sketch\objs.a(fstick.ino.cpp.o):C:\dev\fstick\classes/wifi.h:8: first defined here
collect2.exe: error: ld returned 1 exit status

I'm pretty new in M5Stick C Plus world (even in arduino) - so i'm kind of lost here (tried to google it but no success).

Do you know how can i fix it ?

**Comment by IMXNOOBX** [comment]
You must run first the python script wich will add the necessary compiler flags. Check the Readme step 3

3. Run the python script python3 setup.py to be able to to build the project
