### ISSUE TITLE
-250% battery (bug)

### ISSUE THREAD

**Issue by Niximkk** [IMXNOOBX/fstick#8]
In the "main menu", the battery meter shows -250% in red.

![YXdGs1E1](https://github.com/IMXNOOBX/fstick/assets/85513545/ad700be4-5012-41be-921b-4fd6d79ce55d)

**Comment by IMXNOOBX** [comment]
It will be fixed for the next update!

**Comment by IMXNOOBX** [comment]
fixed in https://github.com/IMXNOOBX/fstick/commit/1226f796b8258f89401fbeea6f501df7e6f4b283 it will be pushed to main soon
